# Generated by Django 3.1.6 on 2022-03-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVS',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('data', models.BinaryField(unique=True)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
