# Generated by Django 3.2.4 on 2021-12-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvs',
            name='name',
            field=models.CharField(default='CVS', max_length=100),
            preserve_default=False,
        ),
    ]
