# Generated by Django 3.0.3 on 2022-03-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220310_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='name',
            field=models.CharField(default='name', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
