# Generated by Django 3.0.3 on 2022-03-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_story_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='project',
        ),
    ]
